print("##############################")
print("#                            #")
print("#    Aliya Raffa Naura Ayu   #")
print("#       2310817120014        #")
print("#                            #")
print("##############################")